# Generated by Django 5.2.6 on 2025-12-17 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dealers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_name', models.CharField(max_length=200, verbose_name='Kampanya Adı')),
                ('budget', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Bütçe (TL)')),
                ('start_date', models.DateField(verbose_name='Başlangıç Tarihi')),
                ('end_date', models.DateField(verbose_name='Bitiş Tarihi')),
                ('platforms', models.JSONField(default=list, verbose_name='Platformlar')),
                ('campaign_type', models.CharField(choices=[('link', 'Link ile Kampanya'), ('upload', 'Görsel Yükleyerek Kampanya')], default='link', max_length=20, verbose_name='Kampanya Türü')),
                ('fb_post_link', models.URLField(blank=True, null=True, verbose_name='Facebook Post Linki')),
                ('ig_post_link', models.URLField(blank=True, null=True, verbose_name='Instagram Post Linki')),
                ('post_images', models.JSONField(blank=True, default=list, verbose_name='Post Görselleri')),
                ('story_images', models.JSONField(blank=True, default=list, verbose_name='Story Görselleri')),
                ('redirect_type', models.CharField(choices=[('satis', 'Satış'), ('servis', 'Servis'), ('diger', 'Diğer')], default='satis', max_length=20, verbose_name='Yönlendirme')),
                ('ad_model', models.CharField(choices=[('bayi_sayfasi', 'Bayi Sayfası'), ('form_yonlendirme', 'Form Doldurma Sayfasına Yönlendirme')], default='bayi_sayfasi', max_length=30, verbose_name='Reklam Modeli')),
                ('notes', models.TextField(blank=True, verbose_name='Notlar')),
                ('status', models.CharField(choices=[('taslak', 'Taslak'), ('onay_bekliyor', 'Onay Bekliyor'), ('onaylandi', 'Onaylandı'), ('reddedildi', 'Reddedildi'), ('yayinda', 'Yayında'), ('tamamlandi', 'Tamamlandı')], default='onay_bekliyor', max_length=20, verbose_name='Durum')),
                ('admin_notes', models.TextField(blank=True, verbose_name='Admin Notları')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_requests', to='dealers.dealer', verbose_name='Dealer')),
            ],
            options={
                'verbose_name': 'Kampanya Talebi',
                'verbose_name_plural': 'Kampanya Talepleri',
                'ordering': ['-created_at'],
            },
        ),
    ]
