# Generated by Django 5.2.6 on 2026-01-20 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignrequest',
            name='ad_model',
            field=models.CharField(choices=[('bayi_sayfasi', 'Bayi Sayfası'), ('form_yonlendirme', 'Form Doldurma Sayfasına Yönlendirme'), ('leasing', 'Leasing')], default='bayi_sayfasi', max_length=30, verbose_name='Reklam Modeli'),
        ),
    ]
