# Generated by Django 5.2.6 on 2026-01-27 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_add_leasing_to_admodel'),
        ('dealers', '0009_add_soft_delete_to_dealer'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignrequest',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaign_requests', to='dealers.brand', verbose_name='Marka'),
        ),
    ]
