# Generated by Django 5.2.6 on 2026-02-11 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_add_brand_to_campaign'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaAdsConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_id', models.CharField(max_length=100, verbose_name='App ID')),
                ('app_secret', models.CharField(max_length=200, verbose_name='App Secret')),
                ('access_token', models.TextField(verbose_name='Access Token')),
                ('ad_account_id', models.CharField(help_text='act_ prefixi ile birlikte, örn: act_123456789', max_length=100, verbose_name='Reklam Hesabı ID')),
                ('default_objective', models.CharField(choices=[('OUTCOME_TRAFFIC', 'Trafik'), ('OUTCOME_ENGAGEMENT', 'Etkileşim'), ('OUTCOME_LEADS', 'Potansiyel Müşteri'), ('OUTCOME_AWARENESS', 'Farkındalık'), ('OUTCOME_SALES', 'Satış')], default='OUTCOME_TRAFFIC', max_length=50, verbose_name='Varsayılan Hedef')),
                ('default_billing_event', models.CharField(choices=[('IMPRESSIONS', 'Gösterim'), ('LINK_CLICKS', 'Tıklama')], default='IMPRESSIONS', max_length=50, verbose_name='Varsayılan Faturalandırma')),
                ('default_optimization_goal', models.CharField(choices=[('REACH', 'Erişim'), ('LINK_CLICKS', 'Bağlantı Tıklamaları'), ('IMPRESSIONS', 'Gösterim'), ('LANDING_PAGE_VIEWS', 'Sayfa Görüntüleme'), ('LEAD_GENERATION', 'Potansiyel Müşteri')], default='REACH', max_length=50, verbose_name='Varsayılan Optimizasyon Hedefi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
            ],
            options={
                'verbose_name': 'Meta Ads Konfigürasyon',
                'verbose_name_plural': 'Meta Ads Konfigürasyon',
            },
        ),
        migrations.AddField(
            model_name='campaignrequest',
            name='ad_message',
            field=models.TextField(blank=True, help_text='Facebook reklamında gösterilecek metin', verbose_name='Reklam Metni'),
        ),
        migrations.AddField(
            model_name='campaignrequest',
            name='cta_type',
            field=models.CharField(choices=[('LEARN_MORE', 'Daha Fazla Bilgi'), ('CONTACT_US', 'İletişime Geç'), ('SHOP_NOW', 'Hemen Al'), ('SIGN_UP', 'Kaydol'), ('GET_QUOTE', 'Teklif Al'), ('BOOK_NOW', 'Randevu Al')], default='LEARN_MORE', max_length=30, verbose_name='Aksiyon Butonu'),
        ),
        migrations.AddField(
            model_name='campaignrequest',
            name='fb_ad_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='FB Ad ID'),
        ),
        migrations.AddField(
            model_name='campaignrequest',
            name='fb_adset_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='FB AdSet ID'),
        ),
        migrations.AddField(
            model_name='campaignrequest',
            name='fb_campaign_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='FB Campaign ID'),
        ),
        migrations.AddField(
            model_name='campaignrequest',
            name='fb_creative_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='FB Creative ID'),
        ),
        migrations.AddField(
            model_name='campaignrequest',
            name='fb_push_error',
            field=models.TextField(blank=True, verbose_name='FB Hata Mesajı'),
        ),
        migrations.AddField(
            model_name='campaignrequest',
            name='fb_push_status',
            field=models.CharField(blank=True, choices=[('pending', 'Bekliyor'), ('pushing', 'Gönderiliyor'), ('success', 'Başarılı'), ('failed', 'Başarısız')], max_length=20, verbose_name='FB Gönderim Durumu'),
        ),
        migrations.AddField(
            model_name='campaignrequest',
            name='fb_pushed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='FB Gönderim Tarihi'),
        ),
        migrations.AddField(
            model_name='campaignrequest',
            name='website_url',
            field=models.URLField(blank=True, help_text="Redirect type'a göre otomatik doldurulur veya manuel girilebilir", null=True, verbose_name='Yönlendirme URL'),
        ),
    ]
