# Generated by Django 5.2.6 on 2026-02-11 14:49

import apps.campaigns.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0004_metaadsconfig_campaignrequest_ad_message_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignCreativeFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=apps.campaigns.models.campaign_creative_upload_path, verbose_name='Dosya')),
                ('file_name', models.CharField(max_length=255, verbose_name='Dosya Adı')),
                ('file_size', models.IntegerField(default=0, verbose_name='Dosya Boyutu (bytes)')),
                ('file_type', models.CharField(choices=[('post', 'Post Görseli'), ('story', 'Story Görseli'), ('video', 'Video')], default='post', max_length=10, verbose_name='Dosya Tipi')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Yüklenme Tarihi')),
                ('campaign_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creative_files', to='campaigns.campaignrequest', verbose_name='Kampanya Talebi')),
            ],
            options={
                'verbose_name': 'Kampanya Kreatif Dosyası',
                'verbose_name_plural': 'Kampanya Kreatif Dosyaları',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
