# Generated by Django 5.2.6 on 2026-02-11 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0005_campaigncreativefile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignrequest',
            name='cta_type',
            field=models.CharField(choices=[('LEARN_MORE', 'Daha Fazla Bilgi'), ('CONTACT_US', 'İletişime Geç'), ('SHOP_NOW', 'Hemen Al'), ('SIGN_UP', 'Kaydol'), ('GET_QUOTE', 'Teklif Al'), ('BOOK_NOW', 'Randevu Al'), ('APPLY_NOW', 'Başvur'), ('CALL_NOW', 'Şimdi Ara'), ('SEND_MESSAGE', 'Mesaj Gönder'), ('WHATSAPP_MESSAGE', 'WhatsApp Mesajı'), ('GET_OFFER', 'Teklifi Al'), ('ORDER_NOW', 'Sipariş Ver'), ('WATCH_MORE', 'Daha Fazla İzle'), ('SUBSCRIBE', 'Abone Ol'), ('DOWNLOAD', 'İndir'), ('NO_BUTTON', 'Buton Yok')], default='LEARN_MORE', max_length=30, verbose_name='Aksiyon Butonu'),
        ),
    ]
