# Generated by Django 5.2.6 on 2026-02-11 15:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0006_alter_campaignrequest_cta_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Oluşturuldu'), ('updated', 'Güncellendi'), ('status_change', 'Durum Değişikliği'), ('fb_push_attempt', 'Facebook Gönderim Denemesi'), ('fb_push_success', 'Facebook Gönderim Başarılı'), ('fb_push_failed', 'Facebook Gönderim Başarısız'), ('fb_status_check', 'Facebook Durum Sorgusu'), ('file_upload', 'Dosya Yüklendi'), ('file_delete', 'Dosya Silindi'), ('note', 'Not Eklendi')], max_length=30, verbose_name='İşlem Tipi')),
                ('message', models.TextField(help_text='Kullanıcıya gösterilecek açıklama', verbose_name='Mesaj')),
                ('details', models.JSONField(blank=True, default=dict, help_text='Ek bilgiler (JSON): hata kodları, API yanıtları, eski/yeni değerler vb.', verbose_name='Detaylar')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Tarih')),
                ('campaign_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='campaigns.campaignrequest', verbose_name='Kampanya Talebi')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaign_activity_logs', to=settings.AUTH_USER_MODEL, verbose_name='İşlemi Yapan')),
            ],
            options={
                'verbose_name': 'Kampanya Aktivite Logu',
                'verbose_name_plural': 'Kampanya Aktivite Logları',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['campaign_request', 'created_at'], name='campaigns_c_campaig_160dbb_idx'), models.Index(fields=['action'], name='campaigns_c_action_ad6e71_idx')],
            },
        ),
    ]
