# Generated by Django 5.2.6 on 2025-12-15 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dealers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisualRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creative_work_request', models.TextField(verbose_name='Creative Work Request')),
                ('quantity_request', models.IntegerField(verbose_name='Quantity Request')),
                ('work_details', models.TextField(verbose_name='Work Details')),
                ('intended_message', models.TextField(blank=True, verbose_name='Intended Message')),
                ('legal_text', models.TextField(blank=True, verbose_name='Legal Text')),
                ('deadline', models.DateField(verbose_name='Deadline')),
                ('reference_image', models.FileField(blank=True, null=True, upload_to='visuals/references/%Y/%m/', verbose_name='Reference Image')),
                ('status', models.CharField(choices=[('gorsel_bekliyor', 'Görsel Bekliyor'), ('bayi_onayi_bekliyor', 'Bayi Onayı Bekliyor'), ('onay_bekliyor', 'Onay Bekliyor (Ingage)'), ('onaylandi', 'Onaylandı'), ('reddedildi', 'Reddedildi'), ('tamamlandi', 'Tamamlandı')], default='gorsel_bekliyor', max_length=30, verbose_name='Durum')),
                ('admin_notes', models.TextField(blank=True, verbose_name='Admin Notları')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visual_requests', to='dealers.dealer', verbose_name='Dealer')),
            ],
            options={
                'verbose_name': 'Görsel İsteği',
                'verbose_name_plural': 'Görsel İstekleri',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VisualRequestCreative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creative_type', models.CharField(choices=[('poster', 'Poster / Afiş'), ('cadir', 'Çadır'), ('tente', 'Tente'), ('stand', 'Stand'), ('orumcek', 'Örümcek Stand'), ('megalight', 'Megalight'), ('dijital', 'Dijital Ekran'), ('led', 'Led Saha Kenarı'), ('rollup', 'Roll-up'), ('el_ilani', 'El İlanı'), ('branda', 'Branda'), ('totem', 'Totem'), ('sticker', 'Sticker'), ('diger', 'Diğer')], max_length=20, verbose_name='Creative Type')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('visual_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creatives', to='visuals.visualrequest', verbose_name='Görsel İsteği')),
            ],
            options={
                'verbose_name': 'Creative Type',
                'verbose_name_plural': 'Creative Types',
            },
        ),
        migrations.CreateModel(
            name='VisualRequestSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=100, verbose_name='Size/Dimension')),
                ('quantity', models.IntegerField(verbose_name='Quantity')),
                ('visual_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='visuals.visualrequest', verbose_name='Görsel İsteği')),
            ],
            options={
                'verbose_name': 'Size',
                'verbose_name_plural': 'Sizes',
            },
        ),
    ]
