# Generated by Django 5.2.6 on 2025-12-16 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visuals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visualrequest',
            name='assigned_to',
            field=models.CharField(blank=True, choices=[('creative_agency', 'Creative Agency'), ('dealer', 'Bayi'), ('brand', 'Marka')], max_length=20, null=True, verbose_name='Atanan Birim'),
        ),
        migrations.AlterField(
            model_name='visualrequest',
            name='status',
            field=models.CharField(choices=[('taslak', 'Taslak'), ('gorsel_bekliyor', 'Görsel Bekliyor'), ('bayi_onayi_bekliyor', 'Bayi Onayı Bekliyor'), ('onay_bekliyor', 'Onay Bekliyor (Ingage)'), ('onaylandi', 'Onaylandı'), ('reddedildi', 'Reddedildi'), ('tamamlandi', 'Tamamlandı')], default='gorsel_bekliyor', max_length=30, verbose_name='Durum'),
        ),
    ]
