# Generated by Django 5.2.6 on 2025-12-16 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visuals', '0002_visualrequest_assigned_to_alter_visualrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='visualrequest',
            name='creative_image',
            field=models.FileField(blank=True, null=True, upload_to='visuals/creatives/%Y/%m/', verbose_name='Creative Image'),
        ),
    ]
