# Generated by Django 5.2.6 on 2025-12-16 04:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visuals', '0003_visualrequest_creative_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisualRequestDeliveredFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='visuals/delivered/%Y/%m/', verbose_name='Dosya')),
                ('file_name', models.CharField(max_length=255, verbose_name='Dosya Adı')),
                ('file_size', models.IntegerField(default=0, verbose_name='Dosya Boyutu (bytes)')),
                ('note', models.TextField(blank=True, verbose_name='Not')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Yüklenme Tarihi')),
                ('visual_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivered_files', to='visuals.visualrequest', verbose_name='Görsel İsteği')),
            ],
            options={
                'verbose_name': 'Teslim Edilen Dosya',
                'verbose_name_plural': 'Teslim Edilen Dosyalar',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='VisualRequestReferenceFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='visuals/references/%Y/%m/', verbose_name='Dosya')),
                ('file_name', models.CharField(max_length=255, verbose_name='Dosya Adı')),
                ('file_size', models.IntegerField(default=0, verbose_name='Dosya Boyutu (bytes)')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Yüklenme Tarihi')),
                ('visual_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reference_files', to='visuals.visualrequest', verbose_name='Görsel İsteği')),
            ],
            options={
                'verbose_name': 'Referans Dosya',
                'verbose_name_plural': 'Referans Dosyalar',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
