# Generated by Django 5.2.6 on 2025-12-16 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visuals', '0004_visualrequestdeliveredfile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visualrequest',
            name='status',
            field=models.CharField(choices=[('taslak', 'Taslak'), ('gorsel_bekliyor', 'Görsel Bekliyor'), ('bayi_onayi_bekliyor', 'Bayi Onayı Bekliyor'), ('onay_bekliyor', 'Onay Bekliyor (Ingage)'), ('onaylandi', 'Onaylandı'), ('reddedildi', 'Reddedildi'), ('tamamlandi', 'Tamamlandı')], default='onay_bekliyor', max_length=30, verbose_name='Durum'),
        ),
    ]
