# Generated by Django 5.2.6 on 2026-01-19 09:59

import apps.visuals.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visuals', '0006_alter_visualrequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visualrequest',
            name='creative_image',
            field=models.FileField(blank=True, null=True, upload_to=apps.visuals.models.visual_creative_upload_path, verbose_name='Creative Image'),
        ),
        migrations.AlterField(
            model_name='visualrequest',
            name='reference_image',
            field=models.FileField(blank=True, null=True, upload_to=apps.visuals.models.visual_reference_upload_path, verbose_name='Reference Image'),
        ),
        migrations.AlterField(
            model_name='visualrequestdeliveredfile',
            name='file',
            field=models.FileField(upload_to=apps.visuals.models.visual_delivered_upload_path, verbose_name='Dosya'),
        ),
        migrations.AlterField(
            model_name='visualrequestreferencefile',
            name='file',
            field=models.FileField(upload_to=apps.visuals.models.visual_reference_upload_path, verbose_name='Dosya'),
        ),
    ]
