# Generated by Django 5.2.6 on 2025-12-15 22:43

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dealer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dealer_code', models.CharField(max_length=50, unique=True, verbose_name='Dealer Code')),
                ('dealer_name', models.CharField(max_length=200, verbose_name='Dealer Name')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('district', models.CharField(max_length=100, verbose_name='District')),
                ('address', models.TextField(verbose_name='Address')),
                ('phone', models.CharField(max_length=20, verbose_name='Phone')),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()], verbose_name='Email')),
                ('contact_person', models.CharField(max_length=200, verbose_name='Contact Person')),
                ('regional_manager', models.CharField(max_length=200, verbose_name='Regional Manager')),
                ('additional_emails', models.JSONField(blank=True, default=list, verbose_name='Additional Emails')),
                ('tax_number', models.CharField(blank=True, max_length=50, verbose_name='Tax Number')),
                ('dealer_type', models.CharField(choices=[('yetkili', 'Yetkili Bayi'), ('anlasmali', 'Anlaşmalı Bayi'), ('satis', 'Satış Bayisi')], default='yetkili', max_length=20, verbose_name='Dealer Type')),
                ('region', models.CharField(blank=True, max_length=100, verbose_name='Region')),
                ('status', models.CharField(choices=[('aktif', 'Aktif'), ('pasif', 'Pasif'), ('askida', 'Askıda')], default='aktif', max_length=20, verbose_name='Status')),
                ('membership_date', models.DateField(auto_now_add=True, verbose_name='Membership Date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
            ],
            options={
                'verbose_name': 'Dealer',
                'verbose_name_plural': 'Dealers',
                'ordering': ['dealer_name'],
            },
        ),
        migrations.CreateModel(
            name='DealerBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Year')),
                ('total_budget', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total Budget')),
                ('used_budget', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Used Budget')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='dealers.dealer', verbose_name='Dealer')),
            ],
            options={
                'verbose_name': 'Dealer Budget',
                'verbose_name_plural': 'Dealer Budgets',
                'ordering': ['-year'],
                'unique_together': {('dealer', 'year')},
            },
        ),
    ]
