# Generated by Django 5.2.6 on 2026-01-13 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DealerBudgetPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Başlangıç Tarihi')),
                ('end_date', models.DateField(verbose_name='Bitiş Tarihi')),
                ('budget_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Bütçe Tutarı')),
                ('used_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Kullanılan Tutar')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Açıklama')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_plans', to='dealers.dealer', verbose_name='Bayi')),
            ],
            options={
                'verbose_name': 'Bütçe Planı',
                'verbose_name_plural': 'Bütçe Planları',
                'ordering': ['start_date'],
            },
        ),
    ]
