# Generated by Django 5.2.6 on 2026-01-13 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealers', '0003_brand_dealer_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='fb_ad_account_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='Facebook Reklam Hesabı ID'),
        ),
        migrations.AddField(
            model_name='brand',
            name='google_ad_account_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='Google Ads Hesabı ID'),
        ),
        migrations.AddField(
            model_name='brand',
            name='ig_ad_account_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='Instagram Reklam Hesabı ID'),
        ),
    ]
