# Generated by Django 5.2.6 on 2026-01-13 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealers', '0004_brand_fb_ad_account_id_brand_google_ad_account_id_and_more'),
    ]

    operations = [
        # contact_person alanı korunuyor - production'da manuel veri taşıma sonrası kaldırılacak
        migrations.AddField(
            model_name='dealer',
            name='contact_first_name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Sorumlu Adı'),
        ),
        migrations.AddField(
            model_name='dealer',
            name='contact_last_name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Sorumlu Soyadı'),
        ),
    ]
