# Generated by Django 5.2.6 on 2026-01-19 09:59

import apps.dealers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealers', '0006_remove_contact_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=apps.dealers.models.brand_logo_upload_path, verbose_name='Logo'),
        ),
    ]
