# Generated by Django 5.2.6 on 2026-01-19 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealers', '0007_dealer_user_foreignkey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealer',
            name='dealer_code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Dealer Code'),
        ),
    ]
