# Generated by Django 5.2.6 on 2026-01-19 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealers', '0008_dealer_code_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealer',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Silinme Tarihi'),
        ),
        migrations.AddField(
            model_name='dealer',
            name='deleted_reason',
            field=models.CharField(blank=True, max_length=255, verbose_name='Silinme Nedeni'),
        ),
        migrations.AddField(
            model_name='dealer',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Silindi'),
        ),
    ]
