# Generated by Django 5.2.6 on 2026-02-11 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealers', '0009_add_soft_delete_to_dealer'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealer',
            name='fb_ad_account_id',
            field=models.CharField(blank=True, help_text='act_ prefixi ile birlikte, örn: act_123456789', max_length=100, verbose_name='Facebook Reklam Hesap ID'),
        ),
        migrations.AddField(
            model_name='dealer',
            name='fb_page_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='Facebook Sayfa ID'),
        ),
        migrations.AddField(
            model_name='dealer',
            name='instagram_account_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='Instagram Hesap ID'),
        ),
        migrations.AddField(
            model_name='dealer',
            name='sales_url',
            field=models.URLField(blank=True, help_text='Kampanyalarda satış yönlendirmesi için kullanılacak URL', null=True, verbose_name='Satış Formu URL'),
        ),
        migrations.AddField(
            model_name='dealer',
            name='service_url',
            field=models.URLField(blank=True, help_text='Kampanyalarda servis yönlendirmesi için kullanılacak URL', null=True, verbose_name='Servis Formu URL'),
        ),
    ]
