# Generated by Django 5.2.6 on 2025-12-16 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('moderator', 'Moderator'), ('bayi', 'Bayi'), ('creative_agency', 'Creative Agency')], default='bayi', max_length=20, verbose_name='Rol'),
        ),
    ]
