# Generated by Django 5.2.6 on 2026-01-13 09:55

import apps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', apps.users.models.ActiveUserManager()),
                ('all_objects', apps.users.models.AllUsersManager()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Silinme Tarihi'),
        ),
        migrations.AddField(
            model_name='user',
            name='deleted_reason',
            field=models.CharField(blank=True, max_length=255, verbose_name='Silinme Nedeni'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Silindi'),
        ),
    ]
