# Generated by Django 5.2.6 on 2026-01-19 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealers', '0007_dealer_user_foreignkey'),
        ('users', '0003_add_soft_delete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dealer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='dealers.dealer', verbose_name='Bayi'),
        ),
    ]
