# Generated by Django 5.2.6 on 2025-12-15 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dealers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncentiveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incentive_title', models.TextField(verbose_name='Incentive Title')),
                ('incentive_details', models.TextField(verbose_name='Incentive Details')),
                ('purpose', models.TextField(verbose_name='Purpose')),
                ('target_audience', models.TextField(verbose_name='Target Audience')),
                ('incentive_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Incentive Amount (TL)')),
                ('proposal_document', models.FileField(upload_to='incentives/documents/%Y/%m/', verbose_name='Proposal Document')),
                ('event_time', models.CharField(max_length=200, verbose_name='Event Time')),
                ('event_location', models.CharField(max_length=200, verbose_name='Event Location (City/District)')),
                ('event_venue', models.CharField(max_length=200, verbose_name='Event Venue Name')),
                ('map_link', models.URLField(blank=True, verbose_name='Map Link')),
                ('performance_metrics', models.TextField(verbose_name='Performance Metrics')),
                ('reference_image', models.FileField(blank=True, null=True, upload_to='incentives/references/%Y/%m/', verbose_name='Reference Image')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('status', models.CharField(choices=[('onay_bekliyor', 'Onay Bekliyor'), ('degerlendirme', 'Değerlendirme'), ('onaylandi', 'Onaylandı'), ('reddedildi', 'Reddedildi'), ('tamamlandi', 'Tamamlandı')], default='onay_bekliyor', max_length=20, verbose_name='Durum')),
                ('admin_notes', models.TextField(blank=True, verbose_name='Admin Notları')),
                ('approved_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Approved Amount (TL)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incentive_requests', to='dealers.dealer', verbose_name='Dealer')),
            ],
            options={
                'verbose_name': 'Teşvik Talebi',
                'verbose_name_plural': 'Teşvik Talepleri',
                'ordering': ['-created_at'],
            },
        ),
    ]
