# Generated by Django 5.2.6 on 2026-01-07 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incentives', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incentiverequest',
            name='event_location',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Event Location (City/District)'),
        ),
        migrations.AlterField(
            model_name='incentiverequest',
            name='event_time',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Event Time'),
        ),
        migrations.AlterField(
            model_name='incentiverequest',
            name='event_venue',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Event Venue Name'),
        ),
        migrations.AlterField(
            model_name='incentiverequest',
            name='incentive_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Incentive Amount (TL)'),
        ),
        migrations.AlterField(
            model_name='incentiverequest',
            name='incentive_details',
            field=models.TextField(blank=True, default='', verbose_name='Incentive Details'),
        ),
        migrations.AlterField(
            model_name='incentiverequest',
            name='incentive_title',
            field=models.TextField(blank=True, default='', verbose_name='Incentive Title'),
        ),
        migrations.AlterField(
            model_name='incentiverequest',
            name='performance_metrics',
            field=models.TextField(blank=True, default='', verbose_name='Performance Metrics'),
        ),
        migrations.AlterField(
            model_name='incentiverequest',
            name='proposal_document',
            field=models.FileField(blank=True, null=True, upload_to='incentives/documents/%Y/%m/', verbose_name='Proposal Document'),
        ),
        migrations.AlterField(
            model_name='incentiverequest',
            name='purpose',
            field=models.TextField(blank=True, default='', verbose_name='Purpose'),
        ),
        migrations.AlterField(
            model_name='incentiverequest',
            name='status',
            field=models.CharField(choices=[('taslak', 'Taslak'), ('onay_bekliyor', 'Onay Bekliyor'), ('degerlendirme', 'Değerlendirme'), ('onaylandi', 'Onaylandı'), ('reddedildi', 'Reddedildi'), ('tamamlandi', 'Tamamlandı')], default='onay_bekliyor', max_length=20, verbose_name='Durum'),
        ),
        migrations.AlterField(
            model_name='incentiverequest',
            name='target_audience',
            field=models.TextField(blank=True, default='', verbose_name='Target Audience'),
        ),
    ]
