# Generated by Django 5.2.6 on 2026-01-19 09:59

import apps.incentives.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incentives', '0002_alter_incentiverequest_event_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incentiverequest',
            name='proposal_document',
            field=models.FileField(blank=True, null=True, upload_to=apps.incentives.models.incentive_document_upload_path, verbose_name='Proposal Document'),
        ),
        migrations.AlterField(
            model_name='incentiverequest',
            name='reference_image',
            field=models.FileField(blank=True, null=True, upload_to=apps.incentives.models.incentive_reference_upload_path, verbose_name='Reference Image'),
        ),
    ]
